In [2]:
#Data Loading and Preprocessing
import pandas as pd
import numpy as np
import ast

df = pd.read_csv("imdb_data (1).csv")
df.columns = df.columns.str.strip().str.lower()

df['budget'] = pd.to_numeric(df['budget'], errors='coerce')
df['revenue'] = pd.to_numeric(df['revenue'], errors='coerce')

df['profit'] = df['revenue'] - df['budget']
df['roi'] = df['profit'] / df['budget']

df = df[df['budget'] > 0]

def get_director(crew_data):
    try:
        crew_list = ast.literal_eval(crew_data)
        for person in crew_list:
            if isinstance(person, dict) and person.get('job') == 'Director':
                return person.get('name')
    except:
        return None

df['director'] = df['crew'].apply(get_director)

df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,status,tagline,title,keywords,cast,crew,revenue,profit,roi,director
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,-0.120382,Steve Pink
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,1.378736,Garry Marshall
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,2.967273,Damien Chazelle
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,12.333333,Sujoy Ghosh
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638,-4738362,-0.592295,Hal Sutherland

In [4]:
#Q1. Highest Profit movie
top_movie = df.loc[df['profit'].idxmax()]

top_movie[['title','profit','production_companies','director','cast']]

title                                                           Furious 7
profit                                                         1316249360
production_companies    [{'name': 'Universal Pictures', 'id': 33}, {'n...
director                                                        James Wan
cast                    [{'cast_id': 17, 'character': 'Dominic Toretto...
Name: 1761, dtype: object

In [5]:
#Q2. Language with Highest Average ROI
roi_language = df.groupby('original_language')['roi'].mean().sort_values(ascending=False)

roi_language.head(1)

original_language
ko    381794.102281
Name: roi, dtype: float64

In [6]:
#Q3. Unique genres
unique_genres = set()

for entry in df['genres'].dropna():
    for g in str(entry).split(','):
        unique_genres.add(g.strip())

unique_genres

{"'name': 'Action'}",
 "'name': 'Action'}]",
 "'name': 'Adventure'}",
 "'name': 'Adventure'}]",
 "'name': 'Animation'}",
 "'name': 'Animation'}]",
 "'name': 'Comedy'}",
 "'name': 'Comedy'}]",
 "'name': 'Crime'}",
 "'name': 'Crime'}]",
 "'name': 'Documentary'}",
 "'name': 'Documentary'}]",
 "'name': 'Drama'}",
 "'name': 'Drama'}]",
 "'name': 'Family'}",
 "'name': 'Family'}]",
 "'name': 'Fantasy'}",
 "'name': 'Fantasy'}]",
 "'name': 'Foreign'}",
 "'name': 'Foreign'}]",
 "'name': 'History'}",
 "'name': 'History'}]",
 "'name': 'Horror'}",
 "'name': 'Horror'}]",
 "'name': 'Music'}",
 "'name': 'Music'}]",
 "'name': 'Mystery'}",
 "'name': 'Mystery'}]",
 "'name': 'Romance'}",
 "'name': 'Romance'}]",
 "'name': 'Science Fiction'}",
 "'name': 'Science Fiction'}]",
 "'name': 'TV Movie'}",
 "'name': 'Thriller'}",
 "'name': 'Thriller'}]",
 "'name': 'War'}",
 "'name': 'War'}]",
 "'name': 'Western'}",
 "'name': 'Western'}]",
 "[{'id': 10402",
 "[{'id': 10749",
 "[{'id': 10751",
 "[{'id': 10752",
 "[{'id': 10769",
 "[{'id': 10770",
 "[{'id': 12",
 "[{'id': 14",
 "[{'id': 16",
 "[{'id': 18",
 "[{'id': 27",
 "[{'id': 28",
 "[{'id': 35",
 "[{'id': 36",
 "[{'id': 37",
 "[{'id': 53",
 "[{'id': 80",
 "[{'id': 878",
 "[{'id': 9648",
 "[{'id': 99",
 "{'id': 10402",
 "{'id': 10749",
 "{'id': 10751",
 "{'id': 10752",
 "{'id': 10769",
 "{'id': 12",
 "{'id': 14",
 "{'id': 16",
 "{'id': 18",
 "{'id': 27",
 "{'id': 28",
 "{'id': 35",
 "{'id': 36",
 "{'id': 37",
 "{'id': 53",
 "{'id': 80",
 "{'id': 878",
 "{'id': 9648",
 "{'id': 99"}

In [7]:
#Q4. Top Producers by ROI
producer_roi = (
    df.groupby('production_companies')['roi']
    .mean()
    .sort_values(ascending=False)
    .head(3)
)

producer_roi

production_companies
[{'name': 'United Artists', 'id': 60}, {'name': 'Charles Chaplin Productions', 'id': 1315}]             8.499999e+06
[{'name': 'Film It Suda', 'id': 5659}]                                                                  4.197476e+06
[{'name': 'Columbia Pictures Corporation', 'id': 441}, {'name': 'Delphi V Productions', 'id': 1174}]    1.018618e+06
Name: roi, dtype: float64

In [8]:
#Q5. Actor with Most Movies
actor_count = {}

for cast_list in df['cast'].dropna():
    for actor in str(cast_list).split(','):
        actor = actor.strip()
        actor_count[actor] = actor_count.get(actor, 0) + 1

top_actor = max(actor_count, key=actor_count.get)

top_actor

"'gender': 2"

In [9]:
#Q6. Actor Analysis
actor_data = df[df['cast'].str.contains(top_actor, na=False)]

actor_data[['title','profit','genres']].head()

,title,profit,genres
0,Hot Tub Time Machine 2,-1685349,"[{'id': 35, 'name': 'Comedy'}]"
1,The Princess Diaries 2: Royal Engagement,55149435,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
2,Whiplash,9792000,"[{'id': 18, 'name': 'Drama'}]"
3,Kahaani,14800000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n..."
5,Pinocchio and the Emperor of the Night,-4738362,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '..."

In [11]:
#Q6. Directors and their Preferred Actors
director_actor_map = {}

for _, row in df.iterrows():
    director = row['director']
    if pd.isna(director):
        continue

    cast_members = str(row['cast']).split(',')

    if director not in director_actor_map:
        director_actor_map[director] = {}

    for actor in cast_members:
        actor = actor.strip()
        director_actor_map[director][actor] = (
            director_actor_map[director].get(actor, 0) + 1
        )

top_directors = df['director'].value_counts().head(3).index

for d in top_directors:
    print("\nDirector:", d)
    print(sorted(director_actor_map[d].items(), key=lambda x: x[1], reverse=True)[:3])

Director: Steven Spielberg
[("'gender': 2", 180), ("'gender': 0", 131), ("'profile_path': None}", 83)]

Director: Clint Eastwood
[("'gender': 2", 134), ("'gender': 0", 107), ("'gender': 1", 56)]

Director: Steven Soderbergh
[("'gender': 2", 95), ("'gender': 1", 32), ("'gender': 0", 21)]